
FROM node:20.12-alpine

WORKDIR /app

COPY package*.json ./
COPY vite.config.* ./
COPY tsconfig.json ./
COPY src ./src
COPY index.html .

RUN npm install
RUN npm run build:client

RUN npm install -g serve

EXPOSE 5173

CMD ["serve", "-s", "dist", "-l", "5173"]